import * as XLSX from "xlsx"
import jsPDF from "jspdf"

export type BookAnalyticsPayload = {
  currency: string
  generated_at: string
  product: {
    id: number
    isbn: string
    title_ar: string
    title_en: string
    price: number | null
    genre: string | null
    author: string | null
    published_at: string | null
  }
  filters: Record<string, unknown>
  summary: Record<string, number>
  by_warehouse: Array<Record<string, unknown>>
  by_channel: Array<Record<string, unknown>>
  discounts: Array<Record<string, unknown>>
  customers: Array<Record<string, unknown>>
  transactions: {
    count: number
    page: number
    page_size: number
    results: Array<Record<string, unknown>>
  }
}

type ExportMeta = {
  generatedBy: string
  generatedAt: string
}

function money(value: unknown, currency = "$") {
  const n = typeof value === "number" ? value : Number(value || 0)
  return `${n.toFixed(3)} ${currency}`
}

function metaRows(payload: BookAnalyticsPayload, meta: ExportMeta): (string | number)[][] {
  return [
    ["Book Sales Analytics"],
    ["Generated at", meta.generatedAt],
    ["Generated by", meta.generatedBy],
    ["Currency", payload.currency],
    ["Product ID", payload.product.id],
    ["ISBN", payload.product.isbn],
    ["Title (EN)", payload.product.title_en],
    ["Title (AR)", payload.product.title_ar],
    ["Filters", JSON.stringify(payload.filters)],
    [],
  ]
}

function summaryRows(payload: BookAnalyticsPayload): (string | number)[][] {
  const s = payload.summary
  const c = payload.currency
  return [
    ["Summary"],
    ["Copies invoiced", s.copies_invoiced],
    ["Copies paid", s.copies_paid],
    ["Copies unpaid", s.copies_unpaid],
    ["Copies returned", s.copies_returned],
    ["Copies complimentary", s.copies_complimentary],
    ["Copies net sold", s.copies_net_sold],
    ["Gross value", money(s.gross_value, c)],
    ["Discount value", money(s.discount_value, c)],
    ["Average discount %", s.average_discount_percent],
    ["Net revenue", money(s.net_revenue, c)],
    ["Amount received", money(s.amount_received, c)],
    ["Amount outstanding", money(s.amount_outstanding, c)],
    ["Returned revenue", money(s.returned_revenue, c)],
    [],
  ]
}

function buildWorkbookRows(payload: BookAnalyticsPayload, meta: ExportMeta): (string | number)[][] {
  const c = payload.currency
  const rows: (string | number)[][] = [
    ...metaRows(payload, meta),
    ...summaryRows(payload),
    ["By warehouse"],
    ["Warehouse", "Sold", "Returned", "Complimentary", "Net", "Net revenue", "Current stock"],
    ...payload.by_warehouse.map((r) => [
      String(r.warehouse_name ?? ""),
      Number(r.copies_sold || 0),
      Number(r.copies_returned || 0),
      Number(r.copies_complimentary || 0),
      Number(r.copies_net || 0),
      money(r.net_revenue, c),
      Number(r.current_stock || 0),
    ]),
    [],
    ["By channel"],
    ["Channel", "Copies", "Net revenue"],
    ...payload.by_channel.map((r) => [
      String(r.channel ?? ""),
      Number(r.copies || 0),
      money(r.net_revenue, c),
    ]),
    [],
    ["Discounts"],
    ["Band", "Copies", "Gross", "Net", "Discount"],
    ...payload.discounts.map((r) => [
      String(r.label ?? ""),
      Number(r.copies || 0),
      money(r.gross_value, c),
      money(r.net_value, c),
      money(r.discount_value, c),
    ]),
    [],
    ["Customers"],
    [
      "Customer",
      "Type",
      "Copies",
      "Returned",
      "Discount",
      "Net",
      "Received",
      "Outstanding",
      "Payment",
      "Last purchase",
      "Repeat",
    ],
    ...payload.customers.map((r) => [
      String(r.customer_name ?? ""),
      String(r.customer_type ?? ""),
      Number(r.copies || 0),
      Number(r.copies_returned || 0),
      money(r.discount_value, c),
      money(r.net_value, c),
      money(r.amount_received, c),
      money(r.amount_outstanding, c),
      String(r.payment_status ?? ""),
      String(r.last_purchase_date ?? ""),
      r.is_repeat ? "Yes" : "No",
    ]),
    [],
    ["Transactions"],
    [
      "Date",
      "Type",
      "Invoice",
      "Customer",
      "Channel",
      "Warehouse",
      "Qty",
      "List price",
      "Discount %",
      "Net",
      "Payment",
      "Returned",
      "Salesperson",
    ],
    ...payload.transactions.results.map((r) => [
      String(r.date ?? ""),
      String(r.transaction_type ?? ""),
      String(r.composite_id ?? ""),
      String(r.customer_name ?? ""),
      String(r.channel ?? ""),
      String(r.warehouse_name ?? ""),
      Number(r.quantity || 0),
      money(r.list_price, c),
      Number(r.discount_percent || 0),
      money(r.net_amount, c),
      String(r.payment_status ?? ""),
      Number(r.returned_quantity || 0),
      String(r.salesperson ?? ""),
    ]),
  ]
  return rows
}

export function downloadBookAnalyticsExcel(
  payload: BookAnalyticsPayload,
  meta: ExportMeta,
  filename: string,
) {
  const rows = buildWorkbookRows(payload, meta)
  const worksheet = XLSX.utils.aoa_to_sheet(rows)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, "Book Analytics")
  XLSX.writeFile(workbook, filename)
}

export function downloadBookAnalyticsCsv(
  payload: BookAnalyticsPayload,
  meta: ExportMeta,
  filename: string,
) {
  const rows = buildWorkbookRows(payload, meta)
  const csv = rows
    .map((row) =>
      row
        .map((cell) => {
          const text = String(cell ?? "")
          if (/[",\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`
          return text
        })
        .join(","),
    )
    .join("\n")
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadBookAnalyticsPdf(
  payload: BookAnalyticsPayload,
  meta: ExportMeta,
  filename: string,
) {
  const doc = new jsPDF()
  const c = payload.currency
  let y = 14
  const line = (text: string, step = 6) => {
    if (y > 280) {
      doc.addPage()
      y = 14
    }
    doc.text(text, 14, y)
    y += step
  }

  doc.setFontSize(14)
  line("Book Sales Analytics", 8)
  doc.setFontSize(10)
  line(`Generated: ${meta.generatedAt}`)
  line(`By: ${meta.generatedBy}`)
  line(`Book: ${payload.product.title_en || payload.product.title_ar} (${payload.product.isbn})`)
  line(`Currency: ${c}`, 8)

  const s = payload.summary
  line(`Invoiced: ${s.copies_invoiced}  |  Net sold: ${s.copies_net_sold}  |  Returned: ${s.copies_returned}`)
  line(`Complimentary: ${s.copies_complimentary}  |  Paid: ${s.copies_paid}  |  Unpaid: ${s.copies_unpaid}`)
  line(`Gross: ${money(s.gross_value, c)}  |  Discount: ${money(s.discount_value, c)}`)
  line(`Net revenue: ${money(s.net_revenue, c)}  |  Received: ${money(s.amount_received, c)}`, 8)

  line("Top customers:")
  payload.customers.slice(0, 8).forEach((row) => {
    line(`- ${row.customer_name}: ${row.copies} copies, ${money(row.net_value, c)}`)
  })

  y += 2
  line("Recent transactions:")
  payload.transactions.results.slice(0, 15).forEach((row) => {
    line(
      `${row.date} | ${row.transaction_type} | #${row.composite_id || "-"} | qty ${row.quantity} | ${money(row.net_amount, c)}`,
    )
  })

  doc.save(filename)
}
